export const FEATURE_VIEWS_AUTH_NAME = 'app.views.auth';
export const LAZY_FEATURE_VIEWS_AUTH_NAME = `lazy.${FEATURE_VIEWS_AUTH_NAME}`;

export const ROUTING_INITIAL_COMPONENT_NAME = LAZY_FEATURE_VIEWS_AUTH_NAME;
