export const FEATURE_VIEWS_HOME_NAME = 'app.views.home';
export const LAZY_FEATURE_VIEWS_HOME_NAME = `lazy.${FEATURE_VIEWS_HOME_NAME}`;

export const ROUTING_INITIAL_COMPONENT_NAME = LAZY_FEATURE_VIEWS_HOME_NAME;
