export const FEATURE_VIEWS_CHAT_NAME = 'app.views.chat';
export const LAZY_FEATURE_VIEWS_CHAT_NAME = `lazy.${FEATURE_VIEWS_CHAT_NAME}`;

export const ROUTING_INITIAL_COMPONENT_NAME = LAZY_FEATURE_VIEWS_CHAT_NAME;
